# Generated by Django 4.0 on 2022-12-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genfk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccess',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='genfk.employee'),
        ),
    ]
